### ISSUE TITLE
failed cytolib installation with 'no matching function for call to 'weakly_canonical''

### ISSUE THREAD

**Issue by marketavlkova** [RGLab/cytolib#51]
I'm trying to install flowCore package using BiocManager, but this fails due to errors in cytolib installation:

```Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.2 (2021-11-01)
Installing package(s) 'flowCore'
also installing the dependency ‘cytolib’

trying URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/cytolib_2.6.0.tar.gz'
Content type 'application/x-gzip' length 5463300 bytes (5.2 MB)
==================================================
downloaded 5.2 MB

trying URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/flowCore_2.6.0.tar.gz'
Content type 'application/x-gzip' length 7356052 bytes (7.0 MB)
==================================================
downloaded 7.0 MB

* installing *source* package ‘cytolib’ ...
** using staged installation
checking for a sed that does not truncate output... /usr/bin/sed
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
configure: Parsing cytolib version info ...
configure: CYTOLIB_VERSION=2.6.0
configure: creating ./config.status
config.status: creating inst/include/cytolib/cytolibConfig.h
config.status: creating src/Makevars
** libs
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c dummy.cpp -o dummy.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/system/src/error_code.cpp -o boost/libs/system/src/error_code.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/codecvt_error_category.cpp -o boost/libs/filesystem/src/codecvt_error_category.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/directory.cpp -o boost/libs/filesystem/src/directory.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/exception.cpp -o boost/libs/filesystem/src/exception.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/operations.cpp -o boost/libs/filesystem/src/operations.o
boost/libs/filesystem/src/operations.cpp:2421:16: error: 
      no matching function for call to 'weakly_canonical'
  path wc_base(weakly_canonical(base, &tmp_ec));
               ^~~~~~~~~~~~~~~~
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:689:13: note: 
      candidate function not viable: no known conversion from
      'boost::system::error_code *' to 'system::error_code &' for 2nd argument;
      remove &
inline path weakly_canonical(path const& p, system::error_code& ec)
            ^
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:163:6: note: 
      candidate function not viable: no known conversion from
      'boost::system::error_code *' to 'const boost::filesystem::path' for 2nd
      argument
path weakly_canonical(path const& p, path const& base, system::error_cod...
     ^
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:684:13: note: 
      candidate function not viable: no known conversion from
      'boost::system::error_code *' to 'const boost::filesystem::path' for 2nd
      argument
inline path weakly_canonical(path const& p, path const& base = current_path())
            ^
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:697:13: note: 
      candidate function not viable: requires 3 arguments, but 2 were provided
inline path weakly_canonical(path const& p, path const& base, system::er...
            ^
boost/libs/filesystem/src/operations.cpp:2424:13: error: 
      no matching function for call to 'weakly_canonical'
  path wc_p(weakly_canonical(p, &tmp_ec));
            ^~~~~~~~~~~~~~~~
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:689:13: note: 
      candidate function not viable: no known conversion from
      'boost::system::error_code *' to 'system::error_code &' for 2nd argument;
      remove &
inline path weakly_canonical(path const& p, system::error_code& ec)
            ^
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:163:6: note: 
      candidate function not viable: no known conversion from
      'boost::system::error_code *' to 'const boost::filesystem::path' for 2nd
      argument
path weakly_canonical(path const& p, path const& base, system::error_cod...
     ^
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:684:13: note: 
      candidate function not viable: no known conversion from
      'boost::system::error_code *' to 'const boost::filesystem::path' for 2nd
      argument
inline path weakly_canonical(path const& p, path const& base = current_path())
            ^
/usr/local/lib/R/4.1/site-library/BH/include/boost/filesystem/operations.hpp:697:13: note: 
      candidate function not viable: requires 3 arguments, but 2 were provided
inline path weakly_canonical(path const& p, path const& base, system::er...
            ^
2 errors generated.
make: *** [boost/libs/filesystem/src/operations.o] Error 1
ERROR: compilation failed for package ‘cytolib’
* removing ‘/usr/local/lib/R/4.1/site-library/cytolib’
ERROR: dependency ‘cytolib’ is not available for package ‘flowCore’
* removing ‘/usr/local/lib/R/4.1/site-library/flowCore’

The downloaded source packages are in
	‘/private/var/folders/qx/vhg6t8_j0fq3bht256ppwffr0000gp/T/RtmpgIfErn/downloaded_packages’
Warning messages:
1: In .inet_warning(msg) :
  installation of package ‘cytolib’ had non-zero exit status
2: In .inet_warning(msg) :
  installation of package ‘flowCore’ had non-zero exit status
```

SessionInfo:

```R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin21.1.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.18/lib/libopenblasp-r0.3.18.dylib
LAPACK: /usr/local/Cellar/r/4.1.2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_2.0.1

loaded via a namespace (and not attached):
 [1] ps_1.6.0            digest_0.6.29       withr_2.4.3        
 [4] R6_2.5.1            evaluate_0.14       highr_0.9          
 [7] rlang_0.4.12        cli_3.1.0           rstudioapi_0.13    
[10] fs_1.5.2            callr_3.7.0         rmarkdown_2.11     
[13] tools_4.1.2         glue_1.6.0          processx_3.5.2     
[16] yaml_2.2.1          fastmap_1.1.0       xfun_0.29          
[19] compiler_4.1.2      BiocManager_1.30.16 clipr_0.7.1        
[22] htmltools_0.5.2     knitr_1.37         
```

**Comment by gfinak** [comment]
I don't see the version of the `BH` package you are running in your sessionInfo, but you may need to check that it's 1.78, and update it if not.

**Comment by marketavlkova** [comment]
My `BH` package version is correct (1.78.0-0):

```
> ip = as.data.frame(installed.packages()[,c(1,3:4)]):
> ip
                    Package    Version    Priority
base64enc         base64enc      0.1-3        <NA>
BH                       BH   1.78.0-0        <NA>
Biobase             Biobase     2.54.0        <NA>
BiocGenerics   BiocGenerics     0.40.0        <NA>
BiocManager     BiocManager    1.30.16        <NA>
BiocVersion     BiocVersion     3.14.0        <NA>
callr                 callr      3.7.0        <NA>
cli                     cli      3.1.0        <NA>
clipr                 clipr      0.7.1        <NA>
colorspace       colorspace      2.0-2        <NA>
digest               digest     0.6.29        <NA>
evaluate           evaluate       0.14        <NA>
farver               farver      2.1.0        <NA>
fastmap             fastmap      1.1.0        <NA>
fs                       fs      1.5.2        <NA>
glue                   glue      1.6.0        <NA>
highr                 highr        0.9        <NA>
htmltools         htmltools      0.5.2        <NA>
jquerylib         jquerylib      0.1.4        <NA>
jsonlite           jsonlite      1.7.2        <NA>
knitr                 knitr       1.37        <NA>
labeling           labeling      0.4.2        <NA>
lifecycle         lifecycle      1.0.1        <NA>
magrittr           magrittr      2.0.1        <NA>
matrixStats     matrixStats     0.61.0        <NA>
munsell             munsell      0.5.0        <NA>
processx           processx      3.5.2        <NA>
ps                       ps      1.6.0        <NA>
R6                       R6      2.5.1        <NA>
RColorBrewer   RColorBrewer      1.1-2        <NA>
Rcpp                   Rcpp      1.0.7        <NA>
RcppArmadillo RcppArmadillo 0.10.7.5.0        <NA>
RcppParallel   RcppParallel      5.1.4        <NA>
reprex               reprex      2.0.1        <NA>
Rhdf5lib           Rhdf5lib     1.16.0        <NA>
rlang                 rlang     0.4.12        <NA>
rmarkdown         rmarkdown       2.11        <NA>
RProtoBufLib   RProtoBufLib      2.6.0        <NA>
rstudioapi       rstudioapi       0.13        <NA>
S4Vectors         S4Vectors     0.32.3        <NA>
scales               scales      1.1.1        <NA>
scatterplot3d scatterplot3d     0.3-41        <NA>
stringi             stringi      1.7.6        <NA>
stringr             stringr      1.4.0        <NA>
tinytex             tinytex       0.36        <NA>
viridisLite     viridisLite      0.4.0        <NA>
withr                 withr      2.4.3        <NA>
xfun                   xfun       0.29        <NA>
yaml                   yaml      2.2.1        <NA>
base                   base      4.1.2        base
boot                   boot     1.3-28 recommended
class                 class     7.3-19 recommended
cluster             cluster      2.1.2 recommended
codetools         codetools     0.2-18 recommended
compiler           compiler      4.1.2        base
datasets           datasets      4.1.2        base
foreign             foreign     0.8-81 recommended
graphics           graphics      4.1.2        base
grDevices         grDevices      4.1.2        base
grid                   grid      4.1.2        base
KernSmooth       KernSmooth    2.23-20 recommended
lattice             lattice    0.20-45 recommended
MASS                   MASS     7.3-54 recommended
Matrix               Matrix      1.4-0 recommended
methods             methods      4.1.2        base
mgcv                   mgcv     1.8-38 recommended
nlme                   nlme    3.1-153 recommended
nnet                   nnet     7.3-16 recommended
parallel           parallel      4.1.2        base
rpart                 rpart     4.1-15 recommended
spatial             spatial     7.3-14 recommended
splines             splines      4.1.2        base
stats                 stats      4.1.2        base
stats4               stats4      4.1.2        base
survival           survival     3.2-13 recommended
tcltk                 tcltk      4.1.2        base
tools                 tools      4.1.2        base
utils                 utils      4.1.2        base
```

**Comment by gfinak** [comment]
Have you tried installing the 3.15 release from this repo?

**Comment by gfinak** [comment]
If  you're on 3.14 and want to stay there then downgrade your BH package to 1.75.

---

Sorry I was wrong, it was just patched for use with 1.78.

**Comment by marketavlkova** [comment]
> If you're on 3.14 and want to stay there then downgrade your BH package to 1.75.

This didn't work, but the error is different after downgrading the BH package:

```
> BiocManager::install("flowCore")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://mirrors.nic.cz/R

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.2 (2021-11-01)
Installing package(s) 'flowCore'
also installing the dependency ‘cytolib’

trying URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/cytolib_2.6.1.tar.gz'
Content type 'application/x-gzip' length 5473994 bytes (5.2 MB)
==================================================
downloaded 5.2 MB

trying URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/flowCore_2.6.0.tar.gz'
Content type 'application/x-gzip' length 7356052 bytes (7.0 MB)
==================================================
downloaded 7.0 MB

* installing *source* package ‘cytolib’ ...
** using staged installation
checking for a sed that does not truncate output... /usr/bin/sed
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
configure: Parsing cytolib version info ...
configure: CYTOLIB_VERSION=2.6.1
configure: creating ./config.status
config.status: creating inst/include/cytolib/cytolibConfig.h
config.status: creating src/Makevars
** libs
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c dummy.cpp -o dummy.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/system/src/error_code.cpp -o boost/libs/system/src/error_code.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/codecvt_error_category.cpp -o boost/libs/filesystem/src/codecvt_error_category.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/directory.cpp -o boost/libs/filesystem/src/directory.o
clang++ -std=gnu++11 -I"/usr/local/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/usr/local/lib/R/4.1/site-library/Rcpp/include' -I'/usr/local/lib/R/4.1/site-library/BH/include' -I'/usr/local/lib/R/4.1/site-library/RProtoBufLib/include' -I'/usr/local/lib/R/4.1/site-library/Rhdf5lib/include' -I'/usr/local/lib/R/4.1/site-library/RcppArmadillo/include' -I'/usr/local/lib/R/4.1/site-library/RcppParallel/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include   -fPIC  -g -O2  -c boost/libs/filesystem/src/exception.cpp -o boost/libs/filesystem/src/exception.o
boost/libs/filesystem/src/exception.cpp:27:41: error: 
      out-of-line definition of 'filesystem_error' does not match any
      declaration in 'boost::filesystem::filesystem_error'
BOOST_FILESYSTEM_DECL filesystem_error::filesystem_error(const char* wha...
                                        ^~~~~~~~~~~~~~~~
boost/libs/filesystem/src/exception.cpp:53:41: error: 
      out-of-line definition of 'filesystem_error' does not match any
      declaration in 'boost::filesystem::filesystem_error'
BOOST_FILESYSTEM_DECL filesystem_error::filesystem_error(const char* wha...
                                        ^~~~~~~~~~~~~~~~
boost/libs/filesystem/src/exception.cpp:79:41: error: 
      out-of-line definition of 'filesystem_error' does not match any
      declaration in 'boost::filesystem::filesystem_error'
BOOST_FILESYSTEM_DECL filesystem_error::filesystem_error(const char* wha...
                                        ^~~~~~~~~~~~~~~~
3 errors generated.
make: *** [boost/libs/filesystem/src/exception.o] Error 1
ERROR: compilation failed for package ‘cytolib’
* removing ‘/usr/local/lib/R/4.1/site-library/cytolib’
ERROR: dependency ‘cytolib’ is not available for package ‘flowCore’
* removing ‘/usr/local/lib/R/4.1/site-library/flowCore’

The downloaded source packages are in
	‘/private/var/folders/qx/vhg6t8_j0fq3bht256ppwffr0000gp/T/Rtmpym4DAq/downloaded_packages’
Old packages: 'BH'
Update all/some/none? [a/s/n]: 
```

I'm going to try installing 3.15 devel. version of Biocondutor then.

**Comment by marketavlkova** [comment]
Oh, I need R version 4.2 in order to be able to install Bioconductor 3.15. Is there really no other way?

**Comment by gfinak** [comment]
You can find the bioconductor build report here:
https://bioconductor.org/checkResults/release/bioc-LATEST/cytolib/
where you can see that the build is working.
For the development version, it's here:
https://bioconductor.org/checkResults/deve/bioc-LATEST/cytolib/

The CI for this repo is running R 4.2 
https://github.com/RGLab/cytolib/runs/4585591963?check_suite_focus=true

I haven't been able to reproduce this on R 4.1 on mac, nor do I have one handy.
But on a linux box with R 4.1.2, cytolib 2.6.1 installs fine with BH 1.78 and Bioconductor 3.14 in my hands.

And indeed no longer compiles with BH 1.75, as it was patched the other day.


I'd suggest giving it another go with BH 1.78 and R 3.14, recompile RProtoBufLib as well.

**Comment by marketavlkova** [comment]
Hmm... I tried to downgrade my R to version 4.0.3, since I wanted to keep R4 and I successfully installed the flowCore package in R 4.0.3 version on macOS HighSierra (10.13.6) before. However on macOS Monterey 12.0.1, I'm getting the same `no matching function for call to 'weakly_canonical'` error during `cytolib` installation in R4.0.3. Is it possible that this is some macOS  Monterey compatibility issue?

**Comment by marketavlkova** [comment]
I updated my macOS to 12.1 - doesn't help with the `cytolib` installation, i.e., gives the same `no matching function for call to 'weakly_canonical'` error as on macOS 12.0.1.

Then I tried to go to the last release of `R` before the release of R version 4 for mac, which is 3.6.3. I used the same workflow as for R@4.0.3 (above), however the installation of R@3.6.3 fails on download error:

```
$ brew extract --version 3.6.3 r homebrew/homebrew-cask
==> Searching repository history
==> Writing formula for r from revision c3a244c to:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Formula/r@3.6.3.rb

$ brew install homebrew/homebrew-cask/r@3.6.3
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
sniffer                                  sqlfluff
==> Updated Formulae
Updated 32 formulae.
==> Updated Casks
Updated 2 casks.

==> Downloading https://cloud.r-project.org/src/contrib/gss_2.1-12.tar.gz
curl: (22) The requested URL returned error: 404

Trying a mirror...
==> Downloading https://mirror.las.iastate.edu/CRAN/src/contrib/gss_2.1-12.tar.g
curl: (22) The requested URL returned error: 404                              

Error: r@3.6.3: Failed to download resource "r@3.6.3--gss"
Download failed: https://mirror.las.iastate.edu/CRAN/src/contrib/gss_2.1-12.tar.gz
```

I tried R@3.6.2 and R@3.5.3, but those fail the same way as R@3.6.3.

Any further suggestions?

**Comment by gfinak** [comment]
I don't see why you're installing r 3.6 as you had  R 4.1
Here's the compatibility for bioconductor 3.13 and 3.14
System compatibility (at the top):
https://bioconductor.org/news/bioc_3_13_release/
https://bioconductor.org/news/bioc_3_14_release/

You can see both require at least R version 4 or 4.1
and Mac os 10.13 or 10.14

You don't need to downgrade R to install older packages.
Older versions of packages are archived;
See "Package Archives" at bottom of this page.
https://bioconductor.org/packages/release/bioc/html/flowCore.html
You can download from there and install via command line `R CMD INSTALL`

Or you can install from the GitHub repo here using `devtools`.



My suggestion, get back on R 4.1.2
Install BioC 3.14 and go from there.

Later I'll be posting a couple new branches of the flow packages here so that cytolib won't depend on BH and maybe that will help you.
But you'll need to install those via devtools or clone the repo and do a local build.

**Comment by marketavlkova** [comment]
Ah, I was installing R@3.6 as you suggested to go to R 3.14 in your previous post. I now get you meant Bioconductor not R...

Anyway, I went back to R@4.1.2, got Bioc.@3.14 and BH@1.78 and installed the flowCore together with cytolib successfully via `BiocManager::install("flowCore")`. So it works now. Thanks!
